name: Deploy

on:
  workflow_call:
    secrets:
      SSH_HOST:
        description: 'SSH host'
        required: true
      SSH_PRIVATE_KEY:
        description: 'SSH private key'
        required: true
      SSH_USER:
        description: 'SSH user'
        required: true


jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -t -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart cocktails-web.service"

      - name: Cleanup
        run: |
          rm -rf ~/.ssh

