name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Test-Build:
    uses: AimbotParce/cocktails-web/.github/workflows/build_test.yaml@main
    with:
      node-version: '20.x'

  Deploy:
    needs: Test Build
    uses: AimbotParce/cocktails-web/.github/workflows/deploy.yaml@main


        

