name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Test Build:
    runs-on: ubuntu-latest

    uses: AimbotParce/cocktails-web/.github/workflows/build_test.yaml@${{secrets.MAIN_BRANCH}}
    with:
      node-version: '20.x'

  Deploy:
    runs-on: ubuntu-latest
    needs: Test Build
    uses: AimbotParce/cocktails-web/.github/workflows/deploy_on_push.yaml@${{secrets.MAIN_BRANCH}}


        

