name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: AimbotParce/cocktails-web/.github/workflows/build_test.yaml@%{{ secrets.MAIN_BRANCH }}
        with:
          node-version: '20.x'

      - name: Deploy
        uses: AimbotParce/cocktails-web/.github/workflows/deploy_on_push.yaml@%{{ secrets.MAIN_BRANCH }}

        

        

